### ISSUE TITLE
server.Shutdown return err

### ISSUE THREAD

**Issue by landrskom** [qa-dev/jsonwire-grid#13]
Check function Shutdown.

**Comment by podtserkovskiy** [comment]
Hi! What's wrong with her?
na locale rabotayet
```
```

**Comment by podtserkovskiy** [comment]
This is the expected behavior
https://github.com/golang/go/blob/47c868dc1c92fcd75ca1574cc5a5fae4797e2271/src/net/http/server.go#L2705
> // Serve always returns a non-nil error. After Shutdown or Close, the
// returned error is ErrServerClosed.
func (srv *Server) Serve(l net.Listener) error {
