### ISSUE TITLE
Сессия отрубается примерно через 2 минуты после старта

### ISSUE THREAD

**Issue by CyHuH** [qa-dev/jsonwire-grid#35]
Использую Appium с иос симулятором

1. Запускаю тесты
2. Начинается запуск сессии, выкачивание/установка приложения и т.д.
3. Примерно через 1.5 - 2 минуты получаю ошибку:
```html
HOOK-ERROR in before_all: WebDriverException: Message: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
HOOK-ERROR in after_all: AttributeError: 'Context' object has no attribute 'driver'
```

в логах грида `http: proxy error: round trip to node: context canceled`

В общем хотелось бы уметь ставить время этого ожидания чуть подольше, чем 1.5 - 2 минуты (хотя бы указать, где в коде это можно поменять)

**Comment by andrskom** [comment]
Спасибо, за подробное описание проблемы. Сейчас посмотрю

**Comment by CyHuH** [comment]
Добавлю, что если убрать из capabilities что-то времязатратное, например `"clearSystemFiles": "true"`, старт сессии укладывается в ~2 минуты и тесты стартуют успешно.

**Comment by andrskom** [comment]
@podtserkovskiy Посмотри пожалуйста транспорт раундтрипера на создание сессии, там он дефолтный, надо сделать конфигурируемым. Там сейчас dialer с таймаутом 30 секунд и idle 90 выставлен(в дефолтном).

**Comment by podtserkovskiy** [comment]
Меня удивляет вот это:
```
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
```
Это не ошибка грида, это ошибка от nginx и возникает она когда сервер на который проксируется запрос, то есть grid отвечает дольше установленного таймаута.
Я думаю проблема решится (или мы увидим истинную ошибку, если она есть) если увеличить таймауты на nginx до времени достаточного на создание сессии в Appium.
Могу лишь предположить что дело в настройках из семейства `proxy_.*_timeout`.
https://nginx.org/ru/docs/http/ngx_http_proxy_module.html
Напишите пожалуйста о том на как изменится ответ после правок таймаутов.

**Comment by andrskom** [comment]
Отлично
@podtserkovskiy Я так понимаю что контекст отваливался из-за того что nginx рвал соединение? Если да то закрой issue, если нет то проверь этот момент.

**Comment by podtserkovskiy** [comment]
Да именно из за этого
