### ISSUE TITLE
Kubernetes resources for selenium nodes

### ISSUE THREAD

**Issue by koltovskikh** [qa-dev/jsonwire-grid#46]
Hello!
Thanks for the wonderful tool, everything started up in the cluster and works fine.
Is it possible to configure resources (requests, limits) for wd-node- * containers? As well as their nodeSelector, tolerations, etc.

**Comment by koltovskikh** [comment]
Ok, I configured resources by default LimitRange in namespace. Now I need to configure nodeSelector

**Comment by koltovskikh** [comment]
We used Kubernetes admission-controllers with plugins: PodTolerationRestriction and PodNodeSelector for configuration all pods in namespace. Issue closed. Thanks.

**Comment by podtserkovskiy** [comment]
Hi, I'm sorry for the late response.
If you want to configure these parameters by the Grid config, Reopen this issue and describe the exact parameters that you want to configure.
